---
jellyfin_enabled: false
jellyfin_dns_accessible: "{{ traefik_enable_dns_for_all }}"
jellyfin_available_externally: false

# directories
jellyfin_config_directory: "{{ docker_home }}/jellyfin/config"
jellyfin_movies_directory: "{{ movies_root }}"
jellyfin_music_directory: "{{ music_root }}"
jellyfin_photos_directory: "{{ photos_root }}"
jellyfin_tv_directory: "{{ tv_root }}"
jellyfin_books_directory: "{{ books_root }}"
jellyfin_audiobooks_directory: "{{ audiobooks_root }}"

# Additional volumes to mount into the jellyfin container
# jellyfin_extra_volumes:
#   - "/path/to/more/media:/path_in_container:ro" # ro = read-only, rw = read-write

# permissions
jellyfin_movies_permissions: "rw"
jellyfin_music_permissions: "rw"
jellyfin_photos_permissions: "rw"
jellyfin_tv_permissions: "rw"
jellyfin_books_permissions: "rw"
jellyfin_audiobooks_permissions: "rw"

# uid / gid
jellyfin_user_id: "1000"
jellyfin_group_id: "1000"

# network
jellyfin_hostname: jellyfin
jellyfin_http_port: 8096

# containers
jellyfin_container_name: jellyfin
jellyfin_image_name: linuxserver/jellyfin
jellyfin_image_version: latest

jellyfin_container_names: # Used to check if app is running
  - "{{ jellyfin_container_name }}"

# specs
jellyfin_memory: 1g
