---
speedtest_tracker_enabled: false
speedtest_tracker_dns_accessible: "{{ traefik_enable_dns_for_all }}"
speedtest_tracker_available_externally: false

# directories
speedtest_tracker_data_directory: "{{ docker_home }}/speedtest_tracker"

# uid / gid
speedtest_tracker_user_id: "1000"
speedtest_tracker_group_id: "1000"

# network
speedtest_tracker_hostname: speedtest-tracker
speedtest_tracker_port: 8765

# containers
speedtest_tracker_container_name: speedtest-tracker
speedtest_tracker_image_name: henrywhitaker3/speedtest-tracker
speedtest_tracker_image_version: latest

speedtest_tracker_container_names: # Used to check if app is running
  - "{{ speedtest_tracker_container_name }}"

# specs
speedtest_tracker_memory: 1g
