---
- name: Start HomeBox
  when: homebox_enabled
  block:
    - name: Check for HomeBox Breaking Changes
      ansible.builtin.include_role:
        name: breaking_changes
      vars:
        breaking_changes_application: homebox

    - name: Create HomeBox Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ homebox_data_directory }}"

    - name: HomeBox Docker Container
      community.docker.docker_container:
        name: "{{ homebox_container_name }}"
        image: "{{ homebox_image_name }}:{{ homebox_image_version }}"
        pull: true
        volumes:
          - "{{ homebox_data_directory }}:/data:rw"
        env:
          HBOX_LOG_LEVEL: "{{ homebox_log_level }}"
          HBOX_LOG_FORMAT: "text"
          HBOX_WEB_MAX_FILE_UPLOAD: "10"
        ports:
          - "{{ homebox_port }}:7745"
        restart_policy: unless-stopped
        memory: "{{ homebox_memory }}"
        labels:
          traefik.enable: "{{ (homebox_dns_accessible or homebox_available_externally) | string }}"
          traefik.http.services.homebox.loadbalancer.server.port: "7745"
          traefik.http.routers.homebox.rule: "Host(`{{ homebox_hostname }}.{{ dns_domain }}`)"
          traefik.http.routers.homebox.tls.domains[0].main: "{{ dns_domain }}"
          traefik.http.routers.homebox.tls.domains[0].sans: "*.{{ dns_domain }}"
          traefik.http.routers.homebox.tls.certresolver: "letsencrypt"
          traefik.http.routers.homebox.middlewares: "{{ omit if homebox_available_externally else 'blockExternal@file' }}"

- name: Stop HomeBox
  when: not homebox_enabled
  block:
    - name: Stop HomeBox
      community.docker.docker_container:
        name: "{{ homebox_container_name }}"
        state: absent
