---
- name: Start Duplicati
  when: duplicati_enabled
  block:
    - name: Check for Duplicati Breaking Changes
      ansible.builtin.include_role:
        name: breaking_changes
      vars:
        breaking_changes_application: duplicati

    - name: Create Duplicati Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ duplicati_data_directory }}"
        - "{{ duplicati_tmp_directory }}"

    - name: Dupicati Docker Container
      vars:
        duplicati_volumes:
          - "/etc/timezone:/etc/timezone:ro"
          - "{{ duplicati_data_directory }}:/data:rw"
          - "{{ data_home }}:/source/data:{{ duplicati_data_permissions }}"
          - "{{ docker_home }}:/source/docker:{{ duplicati_data_permissions }}"
          - "{{ duplicati_tmp_directory }}:/tmp:rw"
        duplicati_volumes_with_extras: "{{ duplicati_volumes + duplicati_extra_volumes | default([]) }}"
      community.docker.docker_container:
        name: "{{ duplicati_container_name }}"
        image: "{{ duplicati_image_name }}:{{ duplicati_image_version }}"
        pull: true
        ports:
          - "{{ duplicati_port }}:8200"
        volumes: "{{ duplicati_volumes_with_extras }}"
        env:
          TZ: "{{ computer_timezone }}"
          PUID: "{{ duplicati_user_id }}"
          PGID: "{{ duplicati_group_id }}"
          SETTINGS_ENCRYPTION_KEY: "{{ duplicati_encryption_key }}"
          DUPLICATI__WEBSERVICE_PASSWORD: "{{ duplicati_webui_password }}"
        restart_policy: unless-stopped
        memory: "{{ duplicati_memory }}"
        labels:
          traefik.enable: "{{ (duplicati_dns_accessible or duplicati_available_externally) | string }}"
          traefik.http.services.duplicati.loadbalancer.server.port: "8200"
          traefik.http.routers.duplicati.rule: "Host(`{{ duplicati_hostname }}.{{ dns_domain }}`)"
          traefik.http.routers.duplicati.tls.domains[0].main: "{{ dns_domain }}"
          traefik.http.routers.duplicati.tls.domains[0].sans: "*.{{ dns_domain }}"
          traefik.http.routers.duplicati.tls.certresolver: "letsencrypt"
          traefik.http.routers.duplicati.middlewares: "{{ omit if duplicati_available_externally else 'blockExternal@file' }}"

- name: Stop Duplicati
  when: not duplicati_enabled
  block:
    - name: Stop Duplicati
      community.docker.docker_container:
        name: "{{ duplicati_container_name }}"
        state: absent
