---
gotify_enabled: false
gotify_dns_accessible: "{{ traefik_enable_dns_for_all }}"
gotify_available_externally: false

# directories
gotify_data_directory: "{{ docker_home }}/gotify"

# network
gotify_hostname: gotify
gotify_port: 2346

# uid / gid
gotify_user_id: "1000"
gotify_group_id: "1000"

# containers
gotify_container_name: gotify
gotify_image_name: gotify/server
gotify_image_version: latest

gotify_container_names: # Used to check if app is running
  - "{{ gotify_container_name }}"

# specs
gotify_memory: 200m
