---
- name: Start Feishin
  when: feishin_enabled
  block:
    - name: Check for Feishin Breaking Changes
      ansible.builtin.include_role:
        name: breaking_changes
      vars:
        breaking_changes_application: feishin

    - name: Feishin Docker Container
      community.docker.docker_container:
        name: "{{ feishin_container_name }}"
        image: "{{ feishin_image_name }}:{{ feishin_image_version }}"
        pull: true
        ports:
          - "{{ feishin_port }}:9180"
        restart_policy: unless-stopped
        memory: "{{ feishin_memory }}"
        labels:
          traefik.enable: "{{ (feishin_dns_accessible or feishin_available_externally) | string }}"
          traefik.http.services.feishin.loadbalancer.server.port: "9180"
          traefik.http.routers.feishin.rule: "Host(`{{ feishin_hostname }}.{{ dns_domain }}`)"
          traefik.http.routers.feishin.tls.domains[0].main: "{{ dns_domain }}"
          traefik.http.routers.feishin.tls.domains[0].sans: "*.{{ dns_domain }}"
          traefik.http.routers.feishin.tls.certresolver: "letsencrypt"
          traefik.http.routers.feishin.middlewares: "{{ omit if feishin_available_externally else 'blockExternal@file' }}"

- name: Stop Feishin
  when: not feishin_enabled
  block:
    - name: Stop Feishin
      community.docker.docker_container:
        name: "{{ feishin_container_name }}"
        state: absent
